# Generated by Django 2.1.3 on 2018-12-30 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jengu', '0001_initial'),
    ]

    operations = [
    ]
