# Generated by Django 2.1.3 on 2019-01-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jengu', '0002_auto_20190123_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
